name: pytype check

on:
  push:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'ubuntu-latest'
          - 'self-hosted'
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v2
    - name: pytypes checker
      uses: theahura/pytypes-action@main
      with:
        args: -d import-error
