name: pytype check
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pytypes checker
      uses: theahura/pytypes-action@main
      with:
        args: -d import-error