name: "pytype check (self-hosted)"

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: "self-hosted"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"
      - name: "Debug: List files before pytype"
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files in $GITHUB_WORKSPACE:"
          ls -laR "$GITHUB_WORKSPACE"
      - name: "pytypes checker"
        uses: "theahura/pytypes-action@main"
        with:
          args: "-d import-error ."
