name: "pytype check (self-hosted)"

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: "self-hosted"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"
      - name: "Debug: List files before pytype"
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files in $GITHUB_WORKSPACE:"
          ls -laR "$GITHUB_WORKSPACE"
      - name: "Debug: List temp files before pytype"
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files in temp:"
          ls -laR "/actions-runner/_work/_temp"
      - name: "Debug: Test Docker action workspace mount"
        run: |
          echo "Host GITHUB_WORKSPACE is: $GITHUB_WORKSPACE"
          echo "Contents of GITHUB_WORKSPACE on host:"
          ls -laR "$GITHUB_WORKSPACE"
          echo "Running basic Docker action to check mounted workspace..."
          # This uses a simple alpine image to list contents of /github/workspace
          # GitHub Actions automatically mounts $GITHUB_WORKSPACE to /github/workspace in Docker actions
          docker run --rm -v "$GITHUB_WORKSPACE:/github/workspace" -w "/github/workspace" \
            alpine sh -c "echo '--- Inside container ---'; pwd; echo 'Contents of /github/workspace:'; ls -laR; echo '--- End of container ---'"
        shell: bash # Ensures $GITHUB_WORKSPACE is expanded correctly
      - name: "TEMP DEBUG: Advanced Docker Mount Test"
        shell: bash
        run: |
          echo "--------------------------------------------------------------------------------"
          echo "DEBUG: Current User: $(id -u -n) (UID $(id -u))"
          echo "DEBUG: GITHUB_WORKSPACE is: $GITHUB_WORKSPACE"
          echo "DEBUG: Contents of GITHUB_WORKSPACE (from runner's perspective):"
          ls -laR "$GITHUB_WORKSPACE"
          echo "--------------------------------------------------------------------------------"
          echo "DEBUG: Creating a test file in a known simple location (/runner_test_data)..."
          # Create as root then change ownership, as runner might not have perms in /
          sudo mkdir -p /runner_test_data
          sudo chown "$(id -u):$(id -g)" /runner_test_data # Use current user/group
          echo "Hello from DinD host" > /runner_test_data/testfile.txt
          echo "DEBUG: Contents of /runner_test_data:"
          ls -laR /runner_test_data
          echo "--------------------------------------------------------------------------------"
          echo "DEBUG: Attempting to mount /runner_test_data into an alpine container..."
          docker run --rm \
            -v "/runner_test_data:/mnt/test_data" \
            -w "/mnt/test_data" \
            alpine sh -c " \
              echo '--- Inside alpine (/runner_test_data mount) ---'; \
              pwd; \
              echo 'Contents:'; \
              ls -laR; \
              echo 'Content of testfile.txt:'; \
              cat testfile.txt || echo 'testfile.txt NOT FOUND'; \
              echo '--- End alpine (/runner_test_data mount) ---' \
            "
          echo "--------------------------------------------------------------------------------"
          echo "DEBUG: Attempting to mount GITHUB_WORKSPACE ($GITHUB_WORKSPACE) into an alpine container again..."
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/github/workspace" \
            -w "/github/workspace" \
            alpine sh -c " \
              echo '--- Inside alpine (GITHUB_WORKSPACE mount) ---'; \
              pwd; \
              echo 'Contents:'; \
              ls -laR; \
              echo '--- End alpine (GITHUB_WORKSPACE mount) ---' \
            "
          echo "--------------------------------------------------------------------------------"
      - name: "pytypes checker"
        uses: "theahura/pytypes-action@main"
        with:
          args: -d import-error
