name: pytype check

# 12

on:
  push:
  pull_request_target:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pytypes checker
      uses: theahura/pytypes-action@main
      with:
        args: -d import-error